FROM node:25.9-trixie AS builder

WORKDIR /app
COPY kanade-web/package.json kanade-web/package-lock.json ./
RUN npm ci
COPY kanade-web/ ./
RUN npm run build

FROM nginx:1.29-trixie
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
